name: amazon_payment_services_apple_pay_example
description: amazon_payment_services_apple_pay_plugin example

version: 0.0.1+1
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  crypto:
  amazon_payment_services_apple_pay:
    path: ../

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
