name: amazon_payment_services_apple_pay
description: Flutter package for Amazon Payment Services native mobile SDKs 
version: 0.0.5
homepage: https://github.com/payfort/flutter-amazonpaymentservices

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AmazonPaymentServicesApplePayPlugin

