#authors : Nabeeh Nabeeh Information Technology

name: amazon_payment_services_apple_pay
description: Flutter package for Amazon Payment Services native mobile SDKs
publish_to: none


homepage: https://github.com/payfort/flutter-amazonpaymentservices
version: 0.0.5


environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  json_annotation:
  json_serializable:
  build_runner:


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: AmazonPaymentServicesApplePayPlugin

